//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseEntities
{
    using System;
    using System.Collections.Generic;
    using System.Configuration;
    using System.Drawing;
    using System.IO;
    using System.Runtime.Serialization.Formatters.Binary;

    [Serializable]
    public partial class Admin : IEquatable<Admin>
    {
        public int Id { get; set; }

        public string Login { get; set; }

        public string Password { get; set; }

        public Status UserStatus { get; set; }

        public Admin()
        {
            Login = "empty";
            Password = "empty";
            UserStatus = Status.NotBanned;
        }

        public Admin (string login, string password) : this()
        {
            Login = login;
            Password = password;
        }

        public bool Equals(Admin other)
        {
            return Login == other.Login && Password == other.Password;
        }
    }
}
